### ISSUE TITLE
Config isn't working for hearthstone durability

### ISSUE THREAD

**Issue by VeggeieDude** [MaxNeedsSnacks/gag#18]
Heya! I changed the durability of both hearthstone and energized hearthstone to 1, but it's still the default 64 and 256 for both respectively. The cooldown and teleport timer config options work though!

I'm on fabric 1.20.1 using version 3.0.0-build.4

**Comment by MaxNeedsSnacks** [comment]
Did you change the option on the server but not on the client by any chance?

**Comment by VeggeieDude** [comment]
> Did you change the option on the server but not on the client by any chance?

Well I'm only using it single player so I guess it'd count as both client and server lol. Or are there 2 different config files for client and server that I missed?

**Comment by MaxNeedsSnacks** [comment]
Nah there's only one file... Oh dear... Alright I'm looking into this

**Comment by VeggeieDude** [comment]
Ah ok lol. Well gl!

**Comment by MaxNeedsSnacks** [comment]
Mh, that's annoying, I just noticed I'm loading the config at server start... yeah that's not gonna work obviously pff. I'm gonna check if there was a good reason for this or whether I just wanted to load the config as late as I can (for example to allow reloading by joining another world)

**Comment by 0culist** [comment]
~~Issue is still present on Minecraft 1.20.1, Forge 47.4.0, Gadgets Against Grind 3.0.0-build.13~~
~~Changed Energised stone durability to 8 on my server and client, but restarting the server and client resulted in it still showing 255/256 durability after using it once.~~

**Comment by 0culist** [comment]
I closed #33 , turns out it was user error. This does, in fact, work as intended
