### ISSUE TITLE
Labeling Tool doesn't work on servers

### ISSUE THREAD

**Issue by 1keponchem** [MaxNeedsSnacks/gag#19]
# Summary
On a server, Labeling Tool doesn't work.
The tool successfully opens, GUI looks normal, and renaming itself works.
But as soon as the renamed item is extracted from the slot, the name reverts to its former name.
If Pigment Jar is used, pigment inside the jar doesn't get consumed.

# Steps to reproduce
1. Join a server with GAG installed
2. Use Labeling Tool and rename item
3. Take out the renamed item from the slot
4. The item's name reverts to its former name

# Versions
Minecraft 1.19.2, Forge 43.3.8
- Architectury API 6.6.92
- FTB Library 1902.4.1-build.236
- Gadgets Against Grind 2.1.0-build.18

**Comment by MaxNeedsSnacks** [comment]
Oh dear, that's an annoying desync. Do you mind testing this on 1.20.1 real quick, I'm not home at the moment but I wonder if there's something that changed there or if I need to fix both versions...

**Comment by 1keponchem** [comment]
Actually I was slightly curious about that so I'm gonna check 1.20.1 as well. Will be back in a few minutes

**Comment by 1keponchem** [comment]
1.20.1 has the same bug.
I'll write the versions of things below.
Minecraft 1.20.1 Forge 47.2.20
- Architechtury API 9.2.14
- FTB Library 2001.1.5
- GAG 3.0.0-build.4

**Comment by 1keponchem** [comment]
And the tool works in 1.20.1 singleplayer. I forgot to say but 1.19.2 singleplayer also had no problem.

p.s. I'll send the server's log as well. This one is 1.20.1.
[latest.log](https://github.com/MaxNeedsSnacks/gag/files/14474015/latest.log)
I don't know this helps, but it repeatedly says "Unknown message ID: gag:rename_item" so...

**Comment by MaxNeedsSnacks** [comment]
Uh... that's weird alright, I guess the packet isn't registered on the server...?

**Comment by 1keponchem** [comment]
FYI, I tested the oldest possible set of mods in 1.19.2 as well and this bug also exists.
Latest, and oldest possible configuration in 1.18.2 also had the same problem.
This bug seems to be from the very first version which added the tool, unfortunately.

**Comment by 1keponchem** [comment]
Fabric 1.20.1 had the same problem as well.

**Comment by 1keponchem** [comment]
Weirdly, throwing Fish Dynamite before renaming fixed the tool.
Here are the logs of the client and the server:
[latest_client.log](https://github.com/MaxNeedsSnacks/gag/files/14481195/latest_client.log)
[latest_server.log](https://github.com/MaxNeedsSnacks/gag/files/14481196/latest_server.log)

On 21:02:32.207, I connected to the server and used the tool, so the server log says "Unknown message ID: gag:rename_item."
Then I threw fish dynamites, and the client log says "Unknown message ID: gag:fishsplosion," and the server log says "Registering C2S receiver with id gag:rename_item."
After that, I used the tool and it worked.

I think the cause of this problem might be related to the timing of registering recievers.
My friend said the register should be called at event while in setup:
https://github.com/MaxNeedsSnacks/gag/blob/1.19.2/main/common/src/main/java/ky/someone/mods/gag/network/GAGNetwork.java#L8-L12
I'm not certain this is true.

**Comment by MaxNeedsSnacks** [comment]
No, your friend is definitely right, this is probably a classloading thing >.>
I already suspected this last night, but was too tired to make a build on 1.19.2, can you verify for me real quick that the JAR in this archive works? (can't upload the JAR itself due to github restrictions)

[Archive.zip](https://github.com/MaxNeedsSnacks/gag/files/14481913/Archive.zip)

**Comment by 1keponchem** [comment]
It crashed before starting.
[latest.log](https://github.com/MaxNeedsSnacks/gag/files/14482381/latest.log)

**Comment by MaxNeedsSnacks** [comment]
What the...

**Comment by MaxNeedsSnacks** [comment]
Okay so the loom version in 1.19.2 is... hopelessly outdated, and the log did say no refmap was loaded, let me try to update Loom and rebuild this...

**Comment by MaxNeedsSnacks** [comment]
Hokay, let's try this again, built on Loom 1.5 this time ^^

[gag-forge-2.1.0-build.9999.jar.zip](https://github.com/MaxNeedsSnacks/gag/files/14482595/gag-forge-2.1.0-build.9999.jar.zip)

**Comment by 1keponchem** [comment]
It worked! :)

**Comment by MaxNeedsSnacks** [comment]
Awesome! Thanks for the heads up then, gotta port this to all applicable versions >.>
