### ISSUE TITLE
for 1.16.5 when

### ISSUE THREAD

**Issue by GlauberBlox** [MaxNeedsSnacks/gag#20]
i want, just make purple color insted of amethyst at the heartstone
i think blackstone from nether substitutes the deepslate one

**Comment by GlauberBlox** [comment]
and also instead of the brute gold block for temporal pouch u can make a block out of 9 ores of gold or just leave it as a normal gold block

**Comment by MaxNeedsSnacks** [comment]
Sorry, I'm not really interested in porting to 1.16.5 right now. There are probably alternative mods you can consider for that version though (and... I'm not sure, but it should be easy enough to port? I just don't have time to do that AND maintain a new version atm)
