### ISSUE TITLE
[1.21.1] Latest Mod Version is not loading

### ISSUE THREAD

**Issue by Periam** [MaxNeedsSnacks/gag#23]
After installing the latest version of the mod for the MC 1.21.1 the games does not launch

neoforge-21.1.37
gag-5.0.0b
jei-1.21.1-neoforge-19.16.4.166
placebo-1.21.1-9.5.1

[crash-2024-09-04_11.13.35-fml.txt](https://github.com/user-attachments/files/16871975/crash-2024-09-04_11.13.35-fml.txt)

**Comment by Gbergz** [comment]
confirmed

**Comment by MaxNeedsSnacks** [comment]
Ugh shadows broke something in a minor update to placebo

**Comment by MaxNeedsSnacks** [comment]
Fixed in the newest CF build

**Comment by Periam** [comment]
The newest version of GAG for 1.21, is requesting the placebo version for MC 1.21
