### ISSUE TITLE
Fishing Dynamite crash

### ISSUE THREAD

**Issue by Gaz492** [MaxNeedsSnacks/gag#25]
When using the fishing dynamite the game crashes and requires you to either restore a backup or enable the ticking entity fixes in neoforge

Reproduce:
1. Obtain fishing dynamite
2. Throw it
3. Game crash when it blows up

Crash log: [crash-2024-10-21_07.59.07-server.txt](https://github.com/user-attachments/files/17456442/crash-2024-10-21_07.59.07-server.txt)

Notes

This happened to me while playing FTB Neotech
Issue has also been reported to FTB https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5990

**Comment by MaxNeedsSnacks** [comment]
Oh dear this may have been a problem for a while...
Gonna have to look through 1.19, 1.20.1, 1.20.4 and 1.21 and fix upward

**Comment by MaxNeedsSnacks** [comment]
Fixed in the newest release, thankfully this only affects 1.20.4 and 1.21
