### ISSUE TITLE
Having two Temporal Pouches in your inventory at once causes the second pouch to reset every 10 seconds.

### ISSUE THREAD

**Issue by HamishWHC** [MaxNeedsSnacks/gag#7]
[Video here.](https://user-images.githubusercontent.com/20359560/211271195-ca246650-ffb2-4429-80a2-e664415fdde7.mov) Other pouch is doing fine.

**Comment by MaxNeedsSnacks** [comment]
That's intentional behaviour, you're not supposed to have more than one pouch in your inventory gathering time simultaneously (I actually wanted to change this in my rework of how they work), which is basically the same as would happen with other Time in A Bottle style mods and items

**Comment by HamishWHC** [comment]
Ah ok. Thanks for the info! Not sure how difficult this is but I'd suggest the pouch's tooltip should say "Only one temporal pouch can gain time in your inventory at once.", and ensure it preserves the time if you pick up a pouch that has time already (while having a pouch already). I wouldn't want to accidentally wipe the extra time from my friend's pouch if I pick it up randomly.
